# Make indicator columns for tags

In [1]:
import pandas as pd
fpath = '/data/storyq/movie_plot_synopses.csv'
data = pd.read_csv(fpath)
data

,imdb_id,title,plot_synopsis,tags,split,synopsis_source
0,tt0057603,I tre volti della paura,Note: this synopsis is for the orginal Italian...,"cult, horror, gothic, murder, atmospheric",train,imdb
1,tt1733125,Dungeons & Dragons: The Book of Vile Darkness,"Two thousand years ago, Nhagruul the Foul, a s...",violence,train,imdb
2,tt0033045,The Shop Around the Corner,"Matuschek's, a gift store in Budapest, is the ...",romantic,test,imdb
3,tt0113862,Mr. Holland's Opus,"Glenn Holland, not a morning person by anyone'...","inspiring, romantic, stupid, feel-good",train,imdb
4,tt0086250,Scarface,"In May 1980, a Cuban man named Tony Montana (A...","cruelty, murder, dramatic, cult, violence, atm...",val,imdb
...,...,...,...,...,...,...
14823,tt0219952,Lucky Numbers,"In 1988 Russ Richards (John Travolta), the wea...","comedy, murder",test,wikipedia
14824,tt1371159,Iron Man 2,"In Russia, the media covers Tony Stark's discl...","good versus evil, violence",train,wikipedia
14825,tt0063443,Play Dirty,During the North African Campaign in World War...,anti war,train,wikipedia
14826,tt0039464,High Wall,Steven Kenet catches his unfaithful wife in th...,murder,test,wikipedia
14827,tt0235166,Against All Hope,"Sometime in the 1950s in Chicago a man, Cecil ...",christian film,test,wikipedia

In [2]:
dummies = pd.get_dummies(data.tags.str.split(', ').apply(pd.Series).stack()).sum(level=0)
dummies

,absurd,action,adult comedy,allegory,alternate history,alternate reality,anti war,atmospheric,autobiographical,avant garde,...,sentimental,storytelling,stupid,suicidal,suspenseful,thought-provoking,tragedy,violence,western,whimsical
0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14823,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14824,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
14825,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14826,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14827,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
modified = pd.concat([data, dummies], axis=1)
modified

,imdb_id,title,plot_synopsis,tags,split,synopsis_source,absurd,action,adult comedy,allegory,...,sentimental,storytelling,stupid,suicidal,suspenseful,thought-provoking,tragedy,violence,western,whimsical
0,tt0057603,I tre volti della paura,Note: this synopsis is for the orginal Italian...,"cult, horror, gothic, murder, atmospheric",train,imdb,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,tt1733125,Dungeons & Dragons: The Book of Vile Darkness,"Two thousand years ago, Nhagruul the Foul, a s...",violence,train,imdb,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,tt0033045,The Shop Around the Corner,"Matuschek's, a gift store in Budapest, is the ...",romantic,test,imdb,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,tt0113862,Mr. Holland's Opus,"Glenn Holland, not a morning person by anyone'...","inspiring, romantic, stupid, feel-good",train,imdb,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,tt0086250,Scarface,"In May 1980, a Cuban man named Tony Montana (A...","cruelty, murder, dramatic, cult, violence, atm...",val,imdb,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14823,tt0219952,Lucky Numbers,"In 1988 Russ Richards (John Travolta), the wea...","comedy, murder",test,wikipedia,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14824,tt1371159,Iron Man 2,"In Russia, the media covers Tony Stark's discl...","good versus evil, violence",train,wikipedia,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
14825,tt0063443,Play Dirty,During the North African Campaign in World War...,anti war,train,wikipedia,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14826,tt0039464,High Wall,Steven Kenet catches his unfaithful wife in th...,murder,test,wikipedia,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14827,tt0235166,Against All Hope,"Sometime in the 1950s in Chicago a man, Cecil ...",christian film,test,wikipedia,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
# Save out
modified.to_csv('/data/storyq/movie_plots.csv', index=False)